name: build

on:
    push:
        branches:
            - '**'
        tags:
            - '!**'
    pull_request:
        branches:
            - '**'

jobs:
    phpstan:
        runs-on: ubuntu-24.04
        name: PHPStan
        steps:
            - name: Checkout
              uses: actions/checkout@v7
            - name: PHPStan
              uses: docker://oskarstark/phpstan-ga
              env:
                  REQUIRE_DEV: true
                  CHECK_PLATFORM_REQUIREMENTS: false
              with:
                  args: analyse
    cs-fixer:
        runs-on: ubuntu-24.04
        name: PHP-CS-Fixer
        steps:
            - name: Checkout
              uses: actions/checkout@v7
            - name: Fix CS
              uses: docker://oskarstark/php-cs-fixer-ga
              with:
                args: --diff --dry-run
    tests:
        runs-on: ubuntu-24.04
        strategy:
            fail-fast: false
            matrix:
                include:
                    - description: 'Lowest'
                      php: '8.2'
                      dependencies: lowest
                    - description: '8.3'
                      php: '8.3'
                    - description: '8.4'
                      php: '8.4'
                    - description: '8.5'
                      php: '8.5'
        name: PHP ${{ matrix.php }} tests (${{ matrix.description }})
        steps:
            - name: Checkout
              uses: actions/checkout@v7
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  extensions: mongodb-stable, pdo_sqlite
            - name: Go for dev dependencies
              run: composer config minimum-stability dev && composer config prefer-stable true
              if: matrix.dev
            - name: Install dependencies
              uses: ramsey/composer-install@v4
              with:
                  dependency-versions: ${{ matrix.dependencies }}
            - name: Run tests
              run: vendor/bin/phpunit --colors=always

